# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

matrix:
  include:
  - r:
      - release
    script:
      - R CMD build
      - R CMD check

  - r:
      - release
    os: osx
    script:
      - R CMD build
      - R CMD check
