# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
cache: packages
warnings_are_errors: false

# environment variables set for all builds
env:
  global:
    - BIOC_USE_DEVEL="FALSE"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"
r:
  - release

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

# for codecov
r_packages:
  - covr

# we need to install BiocInstaller for testing Bioconductor packages
bioc_required: true

# only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'


